### ISSUE TITLE
Support separate color schemes for light and dark mode

### ISSUE THREAD

**Issue by FelixLisczyk** [croian/mouseless-issues#58]
### Problem Description

Currently, Mouseless only supports a single set of colors for the grid and text, defined by `grid_rgba`, `text_rgba`, and related color settings. This creates legibility issues when switching between light and dark mode in macOS, as colors that work well in one mode may be hard to read in the other. For example, black text is readable on light backgrounds but nearly invisible on dark ones, while white text has the opposite problem.

### Proposed Solution

Extend the configuration to support separate color definitions for light and dark mode. The existing color settings would be replaced or supplemented with mode-specific variants. For example:

```yaml
light_mode_colors:
  background_rgba: [0.0, 0.0, 0.0, 0.0]  # Transparent
  grid_rgba: [0.0, 0.0, 0.0, 0.5]  # Black with 50% opacity
  text_rgba: [0.0, 0.0, 0.0, 0.75]  # Black with 75% opacity
  subgrid_rgba: [0.0, 0.0, 0.0, 0.5]
  subgrid_text_rgba: [0.0, 0.0, 0.0, 0.75]
  always_on_subgrid_rgba: [0.0, 0.0, 0.0, 0.25]

dark_mode_colors:
  background_rgba: [0.0, 0.0, 0.0, 0.0]  # Transparent
  grid_rgba: [1.0, 1.0, 1.0, 0.5]  # White with 50% opacity
  text_rgba: [1.0, 1.0, 1.0, 0.75]  # White with 75% opacity
  subgrid_rgba: [1.0, 1.0, 1.0, 0.5]
  subgrid_text_rgba: [1.0, 1.0, 1.0, 0.75]
  always_on_subgrid_rgba: [1.0, 1.0, 1.0, 0.25]
```

The app would automatically switch between these color schemes based on the system's appearance setting. For backward compatibility, the existing color settings could serve as fallbacks if mode-specific colors are not defined.
