### ISSUE TITLE
💥📣 A CALL FOR PRESETS: keymaps, style, and grids! 💥📣 

### ISSUE THREAD

**Issue by croian** [croian/mouseless-issues#85]
hello everyone, i'm looking to add a menu for quick loading of presets for different sections of the config.  if you've customized your keymap, style, and/or grid into something you like, please share it here!  and if relevant, please provide context for who else might find it useful, i.e. what uses cases, hardware, apps, etc that it works well for.

a few quick guidelines:

- to keep things more readable, please only share the parts you've customized and that you think are worth sharing
- you can share a screenshot of the config editor, or text of relevant config file contents (takes more work right now because config file isn't organized)
- if you're sharing a style or grid, please share a screenshot of the overlay to showcase it!

any that cover common user needs will be put into the menu for other to have quick access to, directly in the app.

thank you for your contributions!  you are all very much appreciated 🙏

**Comment by croian** [comment]
I'll start with my fully position-based grid config (not currently possible from the config editor gui) from #1:

```yaml
# qwerty position-based top-level and second-level grid
# - 5x6 grids, 30 mouse_action_key
# - left hand chars first so they occupy the top 3 rows
# - right hand occupies bottom 3 rows

mouse_action_keys: QWERT ASDFG ZXCVB YUIOP HJKL; NM,./
grid_defn:
- border_width: 0.0
  callback: build_cell_strings
  num_cells_x: 5
  num_cells_y: 6
- border_width: 1.0
  callback: build_cell_strings
  num_cells_x: 5
  num_cells_y: 6
- border_width: 0.0
  callback: apply_strings_and_subgrid_to_cells
  num_cells_x: 2
  num_cells_y: 1

subgrid_mouse_action_keys: QWER UIOP ASDF JKL; ZXCV M,./
subgrid_dims:
- 8
- 3
```

![qwerty_position-based_grid](https://github.com/user-attachments/assets/80cd58ea-25eb-47de-b04c-84dcbc46d455)

**Comment by croian** [comment]
paging @sultaz :)

**Comment by vlnn** [comment]
My current setup provides pretty light grid, so it's easy to see what's underneath. Also I minimized the number of keys in the sub grid to the left 5x4 part of the keyboard, so that `12345` is top row (`1` is always on top left) and `ZXCVB` is bottom row (`B` being bottom right). This means I can "click" pretty fast without really reading the rather small hint on subcells.

Sorry, but sharing the whole config as it's pretty hard to diff it. Also it was quite some job to make a screenshot!

<img width="864" alt="CleanShot 2024-12-21 at 13 43 48@2x" src="https://github.com/user-attachments/assets/06665916-8543-4fe7-9e61-bb88cadd6744" />
<img width="864" alt="CleanShot 2024-12-21 at 13 41 33@2x" src="https://github.com/user-attachments/assets/7295d9fa-c561-4ab0-aad0-f995866b6a3a" />

[mouseless.txt](https://github.com/user-attachments/files/18218406/mouseless.txt)

**Comment by NextMerge** [comment]
Sub-grid layout matching Dvorak: `',.PGCRLAOEUHTNS;QJKMWVZ`

![image](https://github.com/user-attachments/assets/8d3a26c9-6793-45fd-ae56-9ce49787ae5b)

**Comment by croian** [comment]
thank you, @vlnn.  i like it --  i hadn't tried position-based columns yet!  will try this out myself :)

and thank you, @NextMerge.  quick translation of position-based grids/subgrids to common layouts is definitely something i want to implement 👍

**Comment by croian** [comment]
and no problem regarding sharing the whole config, @vlnn.  attaching probably keeps the thread more readable!
 
also, yeah, screenshotting is pretty awkward right now 😅 i'm thinking about adding some screenshot utility (also useful for bug reporting) directly in the app, or maybe just configuring by default to allow system screenshot shortcuts to passthrough while the overlay is up

**Comment by LouisLafontaine** [comment]
![Screenshot 2024-12-21 at 20 12 59](https://github.com/user-attachments/assets/fb594b8a-54d0-49e7-91d4-4a238195c65a)

I call it matrix theme lol. I removed the subgrid line, as I found I generally don't rely on them and made the subgrid letters red for more contrast with the rest of the letters (keeping the same color made it confusing). I also adapted the keyboard layout of the subgrid to match colemak-dh layout.

`always_on_subgrid_rgba:
- 1.0
- 1.0
- 1.0
- 0.0
always_show_subgrid: false
app_version: 0.2.1
background_rgba:
- 0.0
- 0.0
- 0.0
- 0.1
classname: AppConfig
font_size_multiplier: 0.6
grid_defn:
- border_width: 0.0
  callback: build_cell_strings
  num_cells_x: 26
  num_cells_y: 1
- border_width: 1.75
  callback: build_cell_strings
  num_cells_x: 1
  num_cells_y: 26
- border_width: 0.0
  callback: apply_strings_and_subgrid_to_cells
  num_cells_x: 2
  num_cells_y: 1
grid_rgba:
- 1.0
- 1.0
- 1.0
- 0.7
hide_cursor_on_click: false
hide_location: bottom_left
keymap:
  close dialog: AltRight
  cycle click count: null
  cycle mouse action type: null
  cycle mouse button: null
  edit config: Tab
  execute mouse action: Space
  hide overlay: AltRight
  hold for drag: CommandLeft
  hold for move: AltLeft
  hold for right button: CommandRight
  release hold/drag: AltRight
  repeat last mouse action: null
  show overlay: CommandLeft tap
  switch monitor left: ShiftLeft tap
  switch monitor right: ShiftRight tap
  toggle overlay: null
mouse_action_keys: ABCDEFGHIJKLMNOPQRSTUVWXYZ
move_duration_ms: 100
move_real_cursor_with_virtual: false
multi_action_timeout_ms: 400
strategy: subgrid
subgrid_dims:
- 8
- 3
subgrid_font_size_multiplier: 0.65
subgrid_mouse_action_keys: QWFPLUY;ARSTNEIOZXCDKH,.
subgrid_rgba:
- 1.0
- 1.0
- 1.0
- 0.0
subgrid_text_rgba:
- 1.0
- 0.0
- 0.0
- 0.8
tap_threshold_ms: 200
text_rgba:
- 0.0
- 0.7
- 0.2
- 1.0
window_opacity: 1.0
`

**Comment by sultaz** [comment]
My set up as large letters for both the main and sub-grid, along with bright red lines to make it easier to see the cells.

![Screenshot 2024-12-26 at 18 02 36](https://github.com/user-attachments/assets/a369748b-fb9c-4b8a-b3bd-45116bf09a30)

```
always_on_subgrid_rgba:
- 1.0
- 1.0
- 1.0
- 0.3
always_show_subgrid: true
app_version: 0.2.0
background_rgba:
- 0.0
- 0.0
- 0.0
- 0.35
classname: AppConfig
font_size_multiplier: 0.6
grid_defn:
- border_width: 0.0
  callback: build_cell_strings
  num_cells_x: 10
  num_cells_y: 3
- border_width: 1.0
  callback: build_cell_strings
  num_cells_x: 3
  num_cells_y: 10
- border_width: 0.0
  callback: apply_strings_and_subgrid_to_cells
  num_cells_x: 2
  num_cells_y: 1
grid_rgba:
- 1.0
- 0.0
- 0.0
- 1.0
hide_cursor_on_click: false
hide_location: top
keymap:
  close dialog: AltRight
  cycle click count: null
  cycle mouse action type: null
  cycle mouse button: null
  edit config: Tab
  execute mouse action: Space tap
  hide overlay: CommandLeft
  hold for drag: CommandLeft
  hold for move: AltLeft
  hold for right button: CommandRight
  release hold/drag: Space
  repeat last mouse action: null
  show overlay: CommandLeft tap
  switch monitor left: ShiftLeft tap
  switch monitor right: ShiftRight tap
  toggle overlay: null
mouse_action_keys: QWERTYUIOPASDFGHJKL;ZXCVBNM,./
move_duration_ms: 100
move_real_cursor_with_virtual: false
multi_action_timeout_ms: 400
strategy: subgrid
subgrid_dims:
- 8
- 3
subgrid_font_size_multiplier: 1.0
subgrid_mouse_action_keys: QWERUIOPASDFJKL;ZXCVM,./
subgrid_rgba:
- 1.0
- 0.0
- 0.0
- 1.0
subgrid_text_rgba:
- 1.0
- 1.0
- 1.0
- 1.0
tap_threshold_ms: 200
text_rgba:
- 1.0
- 1.0
- 1.0
- 1.0
window_opacity: 0.9
```

**Comment by csterritt** [comment]
Something I'd like to see (it doesn't seem to be possible with the current configuration, if I'm reading the documentation correctly) is the ability to adjust the spacing of the letters in the grid.  Right now, it looks like (approximating with ascii):

`A  B | C  D | E  F`

The problem is that the distance from "A" to "B" is apparently the exact same distance as from "B" to "C" (and similarly "C" to "D", "D" to "E", "E" to "F", and so on).

This makes it hard to see where the pairs are - and for me, at least, the grid lines don't provide enough of a clue without taking a moment to orient myself.

If, on the other hand, the letters were spaced like (exaggerated for example):

`A B    |    C D    |    E F`

Then it's immediately obvious that "A" and "B" go together, "C" and "D", "E" and "F", etc.

Again, the above is an exaggeration, I wouldn't want the grid size to change, just the spacing between the letters.

Thanks for considering this!

**Comment by Dracks** [comment]
Hey, 

I discovered this amaizing tool today, since I've got a ultrawide screen (21:9) I tried a diferent aproach, in which the first grid is a direct representation of the keyboard:
```yaml
grid_configs:
- always_show_subgrid: false
  grid_defn:
  - border_width: 0.0
    callback: build_cell_strings
    keys: "qwertyuiop asdfghjkl\xF1 zxcvbnm,.-"
    num_cells_x: 10
    num_cells_y: 3
  - border_width: 1.0
    callback: build_cell_strings
    keys: "QWERT ASDFG ZXCVB YUIOP HJKL\xD1 NM,.-"
    num_cells_x: 5
    num_cells_y: 6
  - border_width: 0.0
    callback: apply_strings_and_subgrid_to_cells
    keys: ''
    num_cells_x: 2
    num_cells_y: 1
```

I expect I will refine it. (Also note, that this is based on Spanish qwerty.
